version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      ci-dependencies:
        dependency-type: 'production'
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
